name: 'Make'
description: 'Run make after go installation'
inputs:
  target:
    description: 'Target for make'
    required: false
    default: 'build'
runs:
  using: "includes"
  steps:
     - includes: actions/setup-go@v2
       with:
         go-version: 1.13

     - name: make
       run: make ${{ inputs.target }}
